import { Meta, SiteFrame } from "@/components/SiteLayout";
import { PageHero } from "@/components/PageHero";
import { useEnquiry } from "@/contexts/EnquiryContext";
import { ArrowRight, Check } from "lucide-react";
import type { ImageFocalPoint } from "@/lib/imageFocal";
import { Link } from "wouter";

type CapabilityType = "manufacturing" | "custom" | "export" | "about";

type CapabilityContent = { eyebrow: string; title: React.ReactNode; description: string; image: string; imageAlt: string; imageFocal?: ImageFocalPoint; label: string; intro: string; points: { title: string; copy: string }[] };

const content: Record<CapabilityType, CapabilityContent> = {
  manufacturing: { eyebrow: "Manufacturing", title: <>Built around <em>material, detail, and delivery.</em></>, description: "Umaid Craftorium is a furniture manufacturer, wholesale supplier, and export company with an 18,000 sq. m manufacturing facility and more than 20 dedicated units in Jodhpur.", image: "/images/official-console.jpg", imageAlt: "Accent table from Umaid Craftorium collection imagery", imageFocal: { desktop: { x: 50, y: 48 }, mobile: { x: 51, y: 43 }, fit: "contain" }, label: "Manufacturing capability", intro: "A B2B operating model for furniture and home-interior orders, with support for product development, sourcing, and quality manufacturing.", points: [{ title: "Furniture categories", copy: "Dining, living, kitchen, bar, bathroom, and outdoor furniture." }, { title: "Quality control", copy: "A four-step quality-control system." }, { title: "Client collaboration", copy: "Close work around specifications and design-development needs." }] },
  custom: { eyebrow: "Custom furniture", title: <>A better brief makes<br />a <em>better starting point.</em></>, description: "Umaid Craftorium publishes product development and sourcing support for client-market needs. Start with a reference, category, or project objective.", image: "/images/official-cabinet.jpg", imageAlt: "Carved wooden cabinet from Umaid Craftorium collection imagery", imageFocal: { desktop: { x: 50, y: 48 }, mobile: { x: 50, y: 43 }, fit: "contain" }, label: "Co-development & sourcing", intro: "Custom work starts with information: a product reference, a floor plan, a finish direction, a quantity range, or simply a clear question. The trade enquiry lets buyers package that context in one place.", points: [{ title: "Discover", copy: "Outline your furniture category, market, or project direction." }, { title: "Develop", copy: "Discuss product development or sourcing needs with the trade team." }, { title: "Review", copy: "Align on requirements and confirm details directly with Umaid Craftorium." }] },
  export: { eyebrow: "Export & trade", title: <>A trade partner for<br /><em>global markets.</em></>, description: "Umaid Craftorium supports worldwide shipping, export operations, and customised container loads for wholesale buyers.", image: "/images/official-trunk.jpg", imageAlt: "Wooden storage chest from Umaid Craftorium collection imagery", imageFocal: { desktop: { x: 50, y: 48 }, mobile: { x: 50, y: 43 }, fit: "contain" }, label: "Export support", intro: "A worldwide furniture, home décor, and accessories offer with container-order support and coordination around client specifications.", points: [{ title: "Worldwide shipping", copy: "Furniture, home décor, and accessories supplied to global markets." }, { title: "Container orders", copy: "Support for customised container loads." }, { title: "Trade enquiries", copy: "A trade-only route for business and project enquiries." }] },
  about: { eyebrow: "About Umaid Craftorium", title: <>A furniture house<br />from <em>Jodhpur.</em></>, description: "Umaid Craftorium is a manufacturer of wholesale furniture and home-interior products, based in Jodhpur, Rajasthan, India.", image: "/images/official-carved-cabinet.jpg", imageAlt: "Carved cabinet from Umaid Craftorium collection imagery", imageFocal: { desktop: { x: 50, y: 48 }, mobile: { x: 50, y: 43 }, fit: "contain" }, label: "Jodhpur, Rajasthan", intro: "The company’s public history describes a business founded around furniture manufacturing and export. Its stated purpose includes creating handmade products across art and craft genres while supporting artisans, craftsmen, and entrepreneurship.", points: [{ title: "Trade-only model", copy: "The published site asks buyers to contact the company for trade enquiries." }, { title: "Artisans & workshops", copy: "The company describes workshops for designers, artisans, and craftspeople." }, { title: "Home & lifestyle", copy: "Published offerings span furniture, home décor, and accessories." }] },
};

export default function CapabilityPage({ type }: { type: CapabilityType }) {
  const page = content[type]; const { openEnquiry } = useEnquiry();
  return <SiteFrame><Meta title={page.eyebrow} description={page.description} /><PageHero eyebrow={page.eyebrow} title={page.title} copy={page.description} image={page.image} imageAlt={page.imageAlt} imageFocal={page.imageFocal} action={{ label: "Start an enquiry", href: "/contact" }} />
    <section className="capability-body section-space"><div className="shell capability-body__grid"><div><p className="eyebrow">{page.label}</p><h2>{page.intro}</h2></div><div className="capability-points">{page.points.map((point, index) => <div key={point.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{point.title}</h3><p>{point.copy}</p></div>)}</div></div></section>
    <section className="capability-cta section-space section-space--sand"><div className="shell capability-cta__inner"><div><p className="eyebrow">Speak to the trade desk</p><h2>Tell us what<br />you’re building.</h2></div><div><p>Use the enquiry flow to collect collection references and share a short project context. If you have an existing brief, include the key requirements in your message.</p><button type="button" className="button button--dark" onClick={openEnquiry}>Start an enquiry <ArrowRight size={17} /></button></div></div></section>
  </SiteFrame>;
}
